# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-26 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20171025_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(blank=True, default='abc', max_length=20),
        ),
    ]
